### ISSUE TITLE
Howto install ? All methods crash on my test

### ISSUE THREAD

**Issue by dcaillibaud** [genomicsengland/vcf-dedup#25]
Hi,

Thanks for this tools, but some lines in the readme about install would be welcome ;-)

I saw that `python3 setup.py …` always throw an exception : 
```
  File "build/bdist.linux-x86_64/egg/vcf_dedup/tools/vcf_transformer.py", line 46
    except Exception, e:
                    ^
SyntaxError: invalid syntax
…
byte-compiling build/bdist.linux-x86_64/egg/vcf_dedup/tests.py to tests.cpython-37.pyc
  File "build/bdist.linux-x86_64/egg/vcf_dedup/tests.py", line 84
    print 1
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(1)?
```

so I tried with python2 `python2 setup.py install`

but then all calls crash.

With `for vcaller in generic strelka starling platypus duplication_finder; do for smethod in af quality allele_calls arbitrary; do vcf_dedupper --input-vcf contacts2019-11-12.vcf --output-vcf contacts2019-11-12.dedup.$vcaller.$smethod.vcf --variant-caller $vcaller --selection-method $smethod --verbose > contacts2019-11-12.dedup.$vcaller.$smethod.log 2>&1; done; done`

all the logs are :

```
2019-11-13 15:19:09,330 INFO Starting the VCF duplication removal...
2019-11-13 15:19:09,331 INFO Initialising VCF transformer...
2019-11-13 15:19:09,331 INFO Input VCF file: contacts2019-11-12.vcf
2019-11-13 15:19:09,331 INFO Output VCF file: contacts2019-11-12.dedup.generic.af.vcf
2019-11-13 15:19:09,334 INFO Initialised!
2019-11-13 15:19:09,334 INFO Starts processing the VCF...
Traceback (most recent call last):
  File "/usr/local/bin/vcf_dedupper", line 4, in <module>
    __import__('pkg_resources').run_script('vcf-dedup==0.4.9', 'vcf_dedupper')
  File "/home/daniel/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/daniel/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vcf_dedup-0.4.9-py2.7.egg/EGG-INFO/scripts/vcf_dedupper", line 83, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/vcf_dedup-0.4.9-py2.7.egg/EGG-INFO/scripts/vcf_dedupper", line 80, in main
    
  File "build/bdist.linux-x86_64/egg/vcf_dedup/runner.py", line 239, in run
  File "build/bdist.linux-x86_64/egg/vcf_dedup/tools/vcf_transformer.py", line 106, in process_vcf
  File "/usr/local/lib/python2.7/dist-packages/PyVCF-0.6.8-py2.7.egg/vcf/parser.py", line 547, in next
    pos = int(row[1])
IndexError: list index out of range
```

Is something missing ?

**Comment by dcaillibaud** [comment]
Ok, sorry for the noise, reading vcf I thought it was about vcard dedup… 
A paragraph about install could be still welcome, and another one about global genomic context too ;-)
